import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { ShoppingCart, Store, Wrench, User, LogOut } from "lucide-react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const handleSignOut = async () => {
    "use server";
    const supabase = createClient();
    await supabase.auth.signOut();
    redirect("/login");
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen flex flex-col">
            {/* Navigation Bar */}
            <nav className="border-b">
              <div className="container mx-auto px-4">
                <div className="flex h-16 items-center justify-between">
                  {/* Logo and Main Navigation */}
                  <div className="flex items-center gap-8">
                    <Link href="/" className="text-xl font-bold">
                      Trueque360
                    </Link>
                    <div className="hidden md:flex items-center gap-6">
                      <Link 
                        href="/products" 
                        className="text-sm font-medium transition-colors hover:text-primary"
                      >
                        Productos
                      </Link>
                      <Link 
                        href="/services" 
                        className="text-sm font-medium transition-colors hover:text-primary"
                      >
                        Servicios
                      </Link>
                      <Link 
                        href="/sellers" 
                        className="text-sm font-medium transition-colors hover:text-primary"
                      >
                        Vendedores
                      </Link>
                    </div>
                  </div>

                  {/* Right Side Navigation */}
                  <div className="flex items-center gap-4">
                    <Link href="/cart">
                      <Button variant="ghost" size="icon">
                        <ShoppingCart className="h-5 w-5" />
                      </Button>
                    </Link>

                    {session ? (
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon">
                            <Avatar className="h-8 w-8">
                              <AvatarImage src={session.user.user_metadata.avatar_url} />
                              <AvatarFallback>
                                {session.user.email?.charAt(0).toUpperCase()}
                              </AvatarFallback>
                            </Avatar>
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="w-56">
                          <DropdownMenuLabel>Mi Cuenta</DropdownMenuLabel>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem asChild>
                            <Link href="/profile" className="flex items-center">
                              <User className="mr-2 h-4 w-4" />
                              Perfil
                            </Link>
                          </DropdownMenuItem>
                          <DropdownMenuItem asChild>
                            <Link href="/orders" className="flex items-center">
                              <ShoppingCart className="mr-2 h-4 w-4" />
                              Mis Pedidos
                            </Link>
                          </DropdownMenuItem>
                          <DropdownMenuItem asChild>
                            <Link href="/services/create" className="flex items-center">
                              <Wrench className="mr-2 h-4 w-4" />
                              Crear Servicio
                            </Link>
                          </DropdownMenuItem>
                          <DropdownMenuItem asChild>
                            <Link href="/sellers/dashboard" className="flex items-center">
                              <Store className="mr-2 h-4 w-4" />
                              Panel de Vendedor
                            </Link>
                          </DropdownMenuItem>
                          <DropdownMenuSeparator />
                          <form action={handleSignOut}>
                            <DropdownMenuItem asChild>
                              <button className="flex w-full items-center text-red-600">
                                <LogOut className="mr-2 h-4 w-4" />
                                Cerrar Sesión
                              </button>
                            </DropdownMenuItem>
                          </form>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    ) : (
                      <div className="flex items-center gap-2">
                        <Link href="/login">
                          <Button variant="ghost">Iniciar Sesión</Button>
                        </Link>
                        <Link href="/register">
                          <Button>Registrarse</Button>
                        </Link>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </nav>

            {/* Main Content */}
            <main className="flex-1">{children}</main>

            {/* Footer */}
            <footer className="border-t py-6">
              <div className="container mx-auto px-4">
                <p className="text-center text-sm text-muted-foreground">
                  © 2024 Store. Todos los derechos reservados.
                </p>
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
